apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
  labels:
    app: drupal
    type: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal
      type: frontend
  template:
    metadata:
      labels:
        app: drupal
        type: frontend
    spec:
      volumes:
        - name: volumen-drupal
          persistentVolumeClaim:
            claimName: pvc-drupal
      containers:
        - name: contenedor-drupal
          image: drupal:9.4-php8.0-apache-bullseye
          ports:
            - containerPort: 80
              name: http-port
            - containerPort: 443
              name: https-port
          volumeMounts:
            - mountPath: /var/www/html/sites/default/files
              name: volumen-drupal